name: CustomAlertsExample
main: CustomAlertsExample\CustomAlertsExample
version: 1.4
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
depend: [CustomAlerts]
load: STARTUP
author: EvolSoft
description: CustomAlerts API implementation example 
website: https://www.evolsoft.tk
