name: CustomAlerts
main: CustomAlerts\CustomAlerts
version: "1.6"
api: [1.12.0]
load: STARTUP
author: EvolSoft
description: Customize alerts (join/leave messages, etc...)
website: http://www.evolsoft.tk

commands:
  customalerts:
    aliases: [calerts]
    description: CustomAlerts Commands.
    permission: customalerts
permissions:
  customalerts:
    default: op
    description: CustomAlerts permissions.
    children:
      customalerts.help:
        default: op
        description: CustomAlerts command Help permission.
      customalerts.info:
        default: op
        description: CustomAlerts command Info permission.
      customalerts.reload:
        default: op
        description: CustomAlerts command Reload permission.
